name: OriginBalloons
version: '1.1.0'
website: ian-tapply.me
author: 'Ian Tapply'
description: 'A recreation of the Origin Realms multi-part cosmetic balloons.'
main: me.iantapply.originballoons.OriginBalloons
api-version: 1.20
commands:
  balloons:
    description: 'Opens up a catalog of balloons to spawn'
    usage: /balloons
    aliases: [balloongui]
  destroyballoon:
    description: 'Destroys the current balloon on a player if they have one'
    usage: /destroyballoon
    aliases: [db]
  spawnballoon:
    description: 'Spawn a balloon.'
    usage: /spawnballoon <balloon>
    aliases: [sb]