name: OriginBalloons
version: '1.0.3'
website: ian-tapply.me
author: 'Ian Tapply'
description: 'A recreation of the Origin Realms multi-part cosmetic balloons.'
main: me.iantapply.originballoons.OriginBalloons
api-version: 1.19
