name: 'Publish JavaDoc'

on:
  push:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    branches: [ "main" ]
    paths: [ '**.java']
  pull_request:
    branches: [ "main" ]
    paths: [ '**.java']
  
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
     - name: Publish JavaDoc
       uses: ren130302/publish-javadoc@test
